resources:
  - name: gds-techops-gameday-git
    type: git
    source:
      uri: git@github.com:tlwr/gds-techops-gameday.git
      branch: wip-tlwr
      private_key: ((read_only_ssh_private_key))

jobs:
  - name: 01-backfill
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: backfill
        config: &backfill-config
          params:
            DB_HOST: ((aws_gameday_one_db_host))
            DB_PASS: ((database_password))
            DB_NAME: app
            DB_USER: app

          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: tlwr/ruby-pg

          inputs:
            - name: gds-techops-gameday-git

          run:
            path: ruby
            dir: gds-techops-gameday-git
            args: ['scripts/backfill-db.rb']
