jobs:
  - name: 01-smoke
    serial: true
    plan:
      - task: smoke
        config: &smoke-config
          params:
            TARGET: https://one.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: tlwr/gds-techops-gameday-lt

          run:
            path: /test/lt

  - name: 02-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://two.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

  - name: 03-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://three.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

  - name: 04-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://four.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

  - name: 05-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://five.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

  - name: 06-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://six.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m

  - name: 07-smoke
    serial: true
    plan:
      - task: smoke
        config:
          <<: *smoke-config
          params:
            TARGET: https://seven.game.gds-reliability.engineering/register
            RPS: 50
            DURATION: 2m
