resources:
  - name: gds-techops-gameday-git
    type: git
    source:
      uri: git@github.com:tlwr/gds-techops-gameday.git
      branch: wip-tlwr
      private_key: ((read_only_ssh_private_key))

jobs:
  - name: 01-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config: &bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-one

          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ruby
              tag: '2.6'

          inputs:
            - name: gds-techops-gameday-git

          run:
            path: ruby
            dir: gds-techops-gameday-git
            args: ['scripts/bootstrap-splunk.rb']

  - name: 02-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-two

  - name: 03-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-three

  - name: 04-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-four

  - name: 05-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-five

  - name: 06-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-six

  - name: 07-bootstrap
    serial: true
    plan:
      - get: gds-techops-gameday-git
      - task: bootstrap
        config:
          <<: *bootstrap-config
          params:
            SPLUNK_URL: https://splunk-admin.zero.game.gds-reliability.engineering
            SPLUNK_PASS: ((splunk_pass))
            IDENTIFIER: gameday-seven
